### PR TITLE
display: use kernel headers

### PR DESCRIPTION
**Pull request by pablomh**
Change-Id: Ie411a4cec638a97e99f27a3e036ff127229bc1f2
Signed-off-by: Erik Castricum <erikcas1972@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
This is not needed since flag is there in vendor repo and also 8994 and 8996 have it to use kernel headers

**Comment by pablomh** [comment]
So do you prefer if I 'unifdef' it?

**Comment by pablomh** [comment]
My problem is that without it it doesn't pick the correct headers:

FAILED: /bin/bash -c "(PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-2690385/bin/clang++ -I hardware/qcom/display/msm8996/libgralloc/../libqdutils -I hardware/qcom/display/msm8996/libgralloc/../libqservice -I hardware/qcom/display/msm8996/libgralloc/../libcopybit -I hardware/qcom/display/msm8996/libgralloc/../sdm/include -I /repos/pablomh/out/target/product/tulip/obj/KERNEL_OBJ/usr/include -I hardware/qcom/display/msm8996/libgralloc -I /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates -I /repos/pablomh/out/target/product/tulip/gen/SHARED_LIBRARIES/libmemalloc_intermediates -I libnativehelper/include/nativehelper \$(cat /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/import_includes) -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem /repos/pablomh/out/target/product/tulip/obj/include -isystem bionic/libc/arch-arm/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/common -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libm/include -isystem bionic/libm/include/arm -c    -fno-exceptions -Wno-multichar -msoft-float -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -mcpu=cortex-a7 -D__ARM_FEATURE_LPAE=1 -mfloat-abi=softfp -mfpu=neon -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -DNDEBUG -g -Wstrict-aliasing=2 -DNDEBUG -UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -nostdlibinc  -target arm-linux-androideabi    -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin    -fvisibility-inlines-hidden -Wsign-promo  -Wno-inconsistent-missing-override -nostdlibinc  -target arm-linux-androideabi   -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing  -fno-rtti -DDEBUG_CALC_FPS -Wno-missing-field-initializers -Wconversion -Wall -Werror -isystem hardware/qcom/display/msm8996/libgralloc/../libgralloc -D__ARM_HAVE_NEON -DLOG_TAG=\\\"qdmemalloc\\\" -Wno-sign-conversion -fPIC -D_USING_LIBCXX -std=gnu++14  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast  -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type    -MD -MF /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.d -o /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.o hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp ) && (cp /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.d /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$//' -e '/^\$/ d' -e 's/\$/ :/' < /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.d >> /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.P; rm -f /repos/pablomh/out/target/product/tulip/obj_arm/SHARED_LIBRARIES/libmemalloc_intermediates/alloc_controller.d )"
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:736:21: error: use of undeclared identifier 'VENUS_Y_META_STRIDE'
    y_meta_stride = VENUS_Y_META_STRIDE(color_format, width);
                    ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:737:21: error: use of undeclared identifier 'VENUS_Y_META_SCANLINES'
    y_meta_height = VENUS_Y_META_SCANLINES(color_format, height);
                    ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:744:21: error: use of undeclared identifier 'VENUS_UV_META_STRIDE'
    c_meta_stride = VENUS_UV_META_STRIDE(color_format, width);
                    ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:745:21: error: use of undeclared identifier 'VENUS_UV_META_SCANLINES'
    c_meta_height = VENUS_UV_META_SCANLINES(color_format, height);
                    ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:753:22: error: use of undeclared identifier 'VENUS_UV_STRIDE'
    ycbcr->cstride = VENUS_UV_STRIDE(color_format, width);
                     ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:816:35: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
                                  COLOR_FMT_NV12_UBWC, ycbcr);
                                  ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:822:35: error: use of undeclared identifier 'COLOR_FMT_NV12_BPP10_UBWC'
                                  COLOR_FMT_NV12_BPP10_UBWC, ycbcr);
                                  ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:984:39: error: unused parameter 'width' [-Werror,-Wunused-parameter]
static void getYuvUBwcWidthHeight(int width, int height, int format,
                                      ^
hardware/qcom/display/msm8996/libgralloc/alloc_controller.cpp:984:50: error: unused parameter 'height' [-Werror,-Wunused-parameter]
static void getYuvUBwcWidthHeight(int width, int height, int format,
                                                 ^
9 errors generated.

**Comment by alviteri** [comment]
Probably it needs to be fixed but the actual system need more love...  I will rework it soon

**Comment by ViperXvenom8888** [comment]
Hello. I'm receiving the same error but under display-caf. How do I fix it?
https://hastebin.com/adaharakec.pas

Thanks!

**Pull request closed without merging**
