### PR TITLE
Fixes for 7.1

### PR DESCRIPTION
**Pull request by pablomh**

### CODE REVIEW

**Comment by alviteri** [comment]
if you have that problem then probably the fix is allocated in kernel side and not here

**Comment by pablomh** [comment]
Please take a look at:

https://github.com/SonyAosp/kernel/commit/49efef0709355757c33ffe019527ce2c2ad79ecd#diff-be4b93d3b37a5a1f73f8430a493afb2dR1794

**Comment by alviteri** [comment]
check marlin kernel and see ? if there is not updated there then can be ok this PR

**Comment by pablomh** [comment]
Marlin kernel has it updated as well:

https://android.googlesource.com/kernel/msm/+blame/android-msm-marlin-3.18-nougat-dr1/include/uapi/video/msm_hdmi_modes.h (line 195)

Modified with: https://android.googlesource.com/kernel/msm/+/49efef0709355757c33ffe019527ce2c2ad79ecd

so I still think the fix is correct.

**Comment by alviteri** [comment]
please be careful with marlin doesn't crash while build and our yeah .... let's see for a proper fix

**Comment by alviteri** [comment]
fixed since you were using 8994 but actual 3.18 requires 8996 hal

**Pull request closed without merging**
